# Copyright 2026-2026 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  # This mirrors the publish command
  build-size-optimized-x64:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - env:
          RUSTFLAGS: "-Zlocation-detail=none -Zfmt-debug=none -L /usr/lib/x86_64-linux-gnu/"
        run: |
          sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          pip install cargo-zigbuild
          cargo +nightly zigbuild \
            -Z build-std=std,panic_abort \
            -Z build-std-features="optimize_for_size" \
            --target x86_64-unknown-linux-gnu.2.17 --release
      
      - uses: actions/upload-artifact@v7
        with:
          name: x64
          path: target/x86_64-unknown-linux-gnu/release/libgsttauriasset.so

  # This mirrors the publish command
  build-size-optimized-arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - env:
          RUSTFLAGS: "-Zlocation-detail=none -Zfmt-debug=none -L /usr/lib/aarch64-linux-gnu/"
        run: |
          sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          pip install cargo-zigbuild
          cargo +nightly zigbuild \
            -Z build-std=std,panic_abort \
            -Z build-std-features="optimize_for_size" \
            --target aarch64-unknown-linux-gnu.2.17 --release

      - uses: actions/upload-artifact@v7
        with:
          name: arm64
          path: target/aarch64-unknown-linux-gnu/release/libgsttauriasset.so
